### ISSUE TITLE
Last update broke my plex server

### ISSUE THREAD

**Issue by IAmNBG** [limetech/docker-templates#23]
My plex server was running fine and then I saw there was an update, after the update the server doesn't work at all and if I try to change any docker settings it just deletes the whole docker. Any idea what's going on? I tried a reboot of the whole server and it didn't solve a thing.

https://gyazo.com/2cb3e465c417e41877643d53bde161b1

**Comment by ljm42** [comment]
Sorry for letting this sit here so long. This Plex container is deprecated, I imagine by now you've resolved the issue :) but for anyone else please use one of the community provided containers available in Community Applications.
